frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'assets-src/**'
          - 'user/**'
          - 'admin/**'
        all-globs-to-all-files:
          - '!user/api/**'
          - '!admin/api/**'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'lib/**'
          - 'user/api/**'
          - 'admin/api/**'

scripts:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

hooks:
  - changed-files:
      - any-glob-to-any-file:
          - 'hooks/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'LICENSE'
          - 'COPYRIGHT'
          - 'LICENSES/**'
          - 'docs/**'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - 'bin/**'
          - 'etc/**'
